stages:
  - build
  - release

variables:
  ELECTRON_FORGE_VERSION: "6.0.0"

# Build Linux packages
build_linux:
  stage: build
  image: node:20
  rules:
    - if: $CI_COMMIT_TAG  # Run this job only when a tag is pushed
  script:
    - apt-get update && apt-get install -y dpkg fakeroot jq npm bash fuse
    - curl -L -o appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
    - chmod +x appimagetool-x86_64.AppImage
    - chmod +x build.sh
    - source build.sh
  artifacts:
    paths:
      - dist/

build_windows:
  stage: build
  image: electronuserland/builder:wine
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    ELECTRON_CACHE: "$CI_PROJECT_DIR/.cache/electron"
    ELECTRON_BUILDER_CACHE: "$CI_PROJECT_DIR/.cache/electron-builder"
  cache:
    paths:
      - node_modules/
      - .cache/electron/
      - .cache/electron-builder/
  script:
    - echo "Installing deps and building Windows package via Wine…"
    - yarn --frozen-lockfile
    - yarn run electron-builder --config builder.yml --win nsis
  artifacts:
    paths:
      - dist/

# Create the GitLab release
create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
  release:  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG for Linux and Windows.'
    assets:
      links:
        - name: "emulsion_x64.exe"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_x64.exe"
        - name: "emulsion_x86_64.AppImage"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_x86_64.AppImage"
        - name: "emulsion_amd64.deb"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_amd64.deb"
  dependencies:
    - upload_artifacts

# Upload assets to GitLab Generic Packages Registry
upload_artifacts:
  stage: release
  image: curlimages/curl:latest  # Use curl to upload files
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Uploading assets for tag $CI_COMMIT_TAG"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion_x64.exe" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_x64.exe"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion_x86_64.AppImage" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_x86_64.AppImage"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion_amd64.deb" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion_amd64.deb"
  dependencies:
    - build_linux
    - build_windows
