stages:
  - build
  - release

variables:
  ELECTRON_FORGE_VERSION: "6.0.0"

# Build Linux packages
build_packages:
  stage: build
  image: node:20
  rules:
    - if: $CI_COMMIT_TAG  # Run this job only when a tag is pushed
  script:
    - apt-get install -y \
        dpkg \
        fakeroot \
        jq \
        npm \
        bash \
        fuse \
        wine \
        wine64 \
        wine32 \
        xvfb \
        libgl1-mesa-glx \
        libglib2.0-0
    - curl -L -o appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
    - chmod +x appimagetool-x86_64.AppImage
    - chmod +x build.sh
    - source build.sh
  artifacts:
    paths:
      - dist/

# Create a GitLab release
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for version $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG - Windows and Linux'
    assets:
      links:
        - name: "emulsion-${CI_COMMIT_TAG}.deb"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-${CI_COMMIT_TAG}.deb"
        - name: "emulsion-${CI_COMMIT_TAG}.AppImage"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-${CI_COMMIT_TAG}.AppImage"
        # Add Windows EXE
        - name: "emulsion-win-${CI_COMMIT_TAG}.exe"
          link_type: "package"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-win-${CI_COMMIT_TAG}.exe"

# Modified upload_assets
upload_assets:
  stage: release
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Uploading assets for tag $CI_COMMIT_TAG"
    # Linux assets
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion-${CI_COMMIT_TAG}.deb" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-${CI_COMMIT_TAG}.deb"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion-${CI_COMMIT_TAG}.AppImage" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-${CI_COMMIT_TAG}.AppImage"
    # Windows EXE
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "dist/emulsion-win-${CI_COMMIT_TAG}.exe" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}/emulsion-win-${CI_COMMIT_TAG}.exe"
  dependencies:
    - build_packages
